config/routes.rb
Rails.application.routes.draw do
  root 'drinklists#index'

  get 'edit', to: 'drinklists#edit_list', as: 'edit_list'
  post 'edit', to: 'drinklists#save_list', as: 'save_list'
  resources :drinklists
end

app/models/bottle.rb
class Bottle < ActiveRecord::Base
  before_save :fix_price

  def fix_price
    self.price = ((purchase_price * 1.25 + 3) / 5).ceil * 5
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drinklists_controller.rb
class DrinklistsController < ApplicationController
  def index
    beer = Bottle.where(category: 'Öl', active: true)
    cider = Bottle.where(category: 'Cider', active: true)
    soda = Bottle.where(category: 'Alkoholfritt', active: true)
    wine = Bottle.where(category: 'Vin', active: true)

    @drinks = {beer: beer}
    # @drinks = {beer: beer, cider: cider, soda: soda, wine: wine}
    @order = ["Lager", "Ale", "American Pale Ale", "IPA", "Pale Ale", "Brown Ale", "Wit", "Porter", "Stout", "Övrigt"]
  end

  def new
    @bottle = Bottle.new
  end

  def create
    @bottle = Bottle.new(bottle_params)

    if @bottle.save
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @bottle = Bottle.find(params[:id])
  end

  def update
    @bottle = Bottle.find(params[:id])

    if @bottle.update(bottle_params)
      redirect_to edit_list_url
    else
      render :edit
    end
  end

  def destroy
    @bottle = Bottle.find(params[:id])

    @bottle.destroy
    redirect_to edit_list_url
  end

  def edit_list
    @bottles = Bottle.all
  end

  def save_list
    Bottle.where.not(id: params[:drinklist_ids]).update_all(active: false)
    Bottle.find(params[:drinklist_ids]).each do |bottle|
      p bottle
      bottle.update(active: true)
    end

    redirect_to edit_list_url
  end

  private
  def bottle_params
    params.require(:bottle).permit(:name, :brand, :category, :category_type, :subtype, :purchase_price, :price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drinklists/_form.html.haml
%table
  / %th Namn
  / %th Märke
  / %th Kategory
  / %th Underkategori
  / %th Kommentar
  / %th Inköpspris
  / %th Pris
  / %th Spara
  %tbody
    = f.hidden_field :id
    %tr
      %th Namn
      %td= f.text_field :name
    %tr
      %th Märke
      %td= f.text_field :brand
    %tr
      %th Kategory
      %td= f.text_field :category
    %tr
      %th Underkategori
      %td= f.text_field :category_type
    %tr
      %th Kommentar
      %td= f.text_field :subtype
    %tr
      %th Inköpspris
      %td= f.text_field :purchase_price
    %tr
      %th Pris
      %td= f.text_field :price
    %tr
      %th Spara
      %td= f.submit "Spara ölbärka"

app/views/drinklists/edit.haml
%h1 Ändra ölbärka

= form_for @bottle, url: { action: :update } do |f|
  = render 'form', f: f

app/views/drinklists/edit_list.haml
.edit
  = form_tag save_list_path do
    .controls
      %button
        = link_to "Tillbaka till listan", root_path
      %button
        = link_to "Ny dryck", new_drinklist_path
      = submit_tag "Spara ändringar"
      %span{:style => "margin-left: 10%;"}
        %b Redigera Ölbärka
    %table
      %thead
        %tr
          %th Aktiv
          %th Namn
          %th Märke
          %th Kategori
          %th Underkategori
          %th Kommentarer
          %th Inköpspris
          %th Pris
          %th Ändra
          %th Ta bort
      %tbody
        - @bottles.each do |d|
          %tr
            %td= check_box_tag "drinklist_ids[]", d.id, d.active
            %td= d.name
            %td= d.brand
            %td= d.category
            %td= d.category_type
            %td= d.subtype
            %td= d.purchase_price
            %td= d.price
            %td
              %button
                = link_to 'Ändra', edit_drinklist_path(id: d.id)
            %td
              %button
                = link_to 'Ta bort', drinklist_path(d), 'data-method' => :delete, class: 'delete', confirm: 'Är du säker?'

app/views/drinklists/index.html.haml
!!!
%html
  %head
    %meta{charset: "UTF-8"}
    %title Dryckeslista
  %body
    #drinklist
      %h1 Ölbärs
      - @drinks.each do |category, list|
        / .drink_category>
        %h1{:class => ["#{category}", "drink_category_title"]}

          / = t(category)
        - list.group_by { |l| l.category_type }.sort_by {|e| @order.index(e.first) }.each do |type, list|
          .subcategory
            - if type != category
              %h2{:class => "#{type}"}
                = type
            %ul.subcategory-list
              - list.sort{ |a, b| a['price'] <=> b['price'] }.each do |drink|
                %li
                  %span= drink['name']
                  %span
                    = drink['price']
                    = ":-"
                  - if drink['subtitle']
                    .subtitle
                      = drink['subtitle']

app/views/drinklists/new.html.haml
%h1 Ny dryck

= form_for @bottle, url: drinklists_path do |f|
  = render 'form', f: f

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>dgenerate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <script src="https://use.typekit.net/kcg2yub.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
<%= yield %>

</body>
</html>